<template>
  <div class="api-layout">
    <doc-content></doc-content>

    <div class="emulated-phone">
      <m-title type="1">Icon</m-title>
      <p class="mtui-p">图标使用开源的Ionicons，版本是2.0.1。更多信息请查看<a class="mtui-link" href="https://ionicons.com/">Ionicons官网</a></p>
      <m-grid :col="3">
        <m-grid-item icon="alert" text="alert" />
        <m-grid-item icon="alert-circled" text="alert-circled" />
        <m-grid-item icon="android-add" text="android-add" />
        <m-grid-item icon="android-add-circle" text="android-add-circle" />
        <m-grid-item icon="android-alarm-clock" text="android-alarm-clock" />
        <m-grid-item icon="android-alert" text="android-alert" />
        <m-grid-item icon="android-apps" text="android-apps" />
        <m-grid-item icon="android-archive" text="android-archive" />
        <m-grid-item icon="android-arrow-back" text="android-arrow-back" />
        <m-grid-item icon="android-arrow-down" text="android-arrow-down" />
        <m-grid-item icon="android-arrow-dropdown" text="android-arrow-dropdown" />
        <m-grid-item icon="android-arrow-dropdown-circle" text="android-arrow-dropdown-circle" />
        <m-grid-item icon="android-arrow-dropleft" text="android-arrow-dropleft" />
        <m-grid-item icon="android-arrow-dropleft-circle" text="android-arrow-dropleft-circle" />
        <m-grid-item icon="android-arrow-dropright" text="android-arrow-dropright" />
        <m-grid-item icon="android-arrow-dropright-circle" text="android-arrow-dropright-circle" />
        <m-grid-item icon="android-arrow-dropup" text="android-arrow-dropup" />
        <m-grid-item icon="android-arrow-dropup-circle" text="android-arrow-dropup-circle" />
        <m-grid-item icon="android-arrow-forward" text="android-arrow-forward" />
        <m-grid-item icon="android-arrow-up" text="android-arrow-up" />
        <m-grid-item icon="android-attach" text="android-attach" />
        <m-grid-item icon="android-bar" text="android-bar" />
        <m-grid-item icon="android-bicycle" text="android-bicycle" />
        <m-grid-item icon="android-boat" text="android-boat" />
        <m-grid-item icon="android-bookmark" text="android-bookmark" />
        <m-grid-item icon="android-bulb" text="android-bulb" />
        <m-grid-item icon="android-bus" text="android-bus" />
        <m-grid-item icon="android-calendar" text="android-calendar" />
        <m-grid-item icon="android-call" text="android-call" />
        <m-grid-item icon="android-camera" text="android-camera" />
        <m-grid-item icon="android-cancel" text="android-cancel" />
        <m-grid-item icon="android-car" text="android-car" />
        <m-grid-item icon="android-cart" text="android-cart" />
        <m-grid-item icon="android-chat" text="android-chat" />
        <m-grid-item icon="android-checkbox" text="android-checkbox" />
        <m-grid-item icon="android-checkbox-blank" text="android-checkbox-blank" />
        <m-grid-item icon="android-checkbox-outline" text="android-checkbox-outline" />
        <m-grid-item icon="android-checkbox-outline-blank" text="android-checkbox-outline-blank" />
        <m-grid-item icon="android-checkmark-circle" text="android-checkmark-circle" />
        <m-grid-item icon="android-clipboard" text="android-clipboard" />
        <m-grid-item icon="android-close" text="android-close" />
        <m-grid-item icon="android-cloud" text="android-cloud" />
        <m-grid-item icon="android-cloud-circle" text="android-cloud-circle" />
        <m-grid-item icon="android-cloud-done" text="android-cloud-done" />
        <m-grid-item icon="android-cloud-outline" text="android-cloud-outline" />
        <m-grid-item icon="android-color-palette" text="android-color-palette" />
        <m-grid-item icon="android-compass" text="android-compass" />
        <m-grid-item icon="android-contact" text="android-contact" />
        <m-grid-item icon="android-contacts" text="android-contacts" />
        <m-grid-item icon="android-contract" text="android-contract" />
        <m-grid-item icon="android-create" text="android-create" />
        <m-grid-item icon="android-delete" text="android-delete" />
        <m-grid-item icon="android-desktop" text="android-desktop" />
        <m-grid-item icon="android-document" text="android-document" />
        <m-grid-item icon="android-done" text="android-done" />
        <m-grid-item icon="android-done-all" text="android-done-all" />
        <m-grid-item icon="android-download" text="android-download" />
        <m-grid-item icon="android-drafts" text="android-drafts" />
        <m-grid-item icon="android-exit" text="android-exit" />
        <m-grid-item icon="android-expand" text="android-expand" />
        <m-grid-item icon="android-favorite" text="android-favorite" />
        <m-grid-item icon="android-favorite-outline" text="android-favorite-outline" />
        <m-grid-item icon="android-film" text="android-film" />
        <m-grid-item icon="android-folder" text="android-folder" />
        <m-grid-item icon="android-folder-open" text="android-folder-open" />
        <m-grid-item icon="android-funnel" text="android-funnel" />
        <m-grid-item icon="android-globe" text="android-globe" />
        <m-grid-item icon="android-hand" text="android-hand" />
        <m-grid-item icon="android-hangout" text="android-hangout" />
        <m-grid-item icon="android-happy" text="android-happy" />
        <m-grid-item icon="android-home" text="android-home" />
        <m-grid-item icon="android-image" text="android-image" />
        <m-grid-item icon="android-laptop" text="android-laptop" />
        <m-grid-item icon="android-list" text="android-list" />
        <m-grid-item icon="android-locate" text="android-locate" />
        <m-grid-item icon="android-lock" text="android-lock" />
        <m-grid-item icon="android-mail" text="android-mail" />
        <m-grid-item icon="android-map" text="android-map" />
        <m-grid-item icon="android-menu" text="android-menu" />
        <m-grid-item icon="android-microphone" text="android-microphone" />
        <m-grid-item icon="android-microphone-off" text="android-microphone-off" />
        <m-grid-item icon="android-more-horizontal" text="android-more-horizontal" />
        <m-grid-item icon="android-more-vertical" text="android-more-vertical" />
        <m-grid-item icon="android-navigate" text="android-navigate" />
        <m-grid-item icon="android-notifications" text="android-notifications" />
        <m-grid-item icon="android-notifications-none" text="android-notifications-none" />
        <m-grid-item icon="android-notifications-off" text="android-notifications-off" />
        <m-grid-item icon="android-open" text="android-open" />
        <m-grid-item icon="android-options" text="android-options" />
        <m-grid-item icon="android-people" text="android-people" />
        <m-grid-item icon="android-person" text="android-person" />
        <m-grid-item icon="android-person-add" text="android-person-add" />
        <m-grid-item icon="android-phone-landscape" text="android-phone-landscape" />
        <m-grid-item icon="android-phone-portrait" text="android-phone-portrait" />
        <m-grid-item icon="android-pin" text="android-pin" />
        <m-grid-item icon="android-plane" text="android-plane" />
        <m-grid-item icon="android-playstore" text="android-playstore" />
        <m-grid-item icon="android-print" text="android-print" />
        <m-grid-item icon="android-radio-button-off" text="android-radio-button-off" />
        <m-grid-item icon="android-radio-button-on" text="android-radio-button-on" />
        <m-grid-item icon="android-refresh" text="android-refresh" />
        <m-grid-item icon="android-remove" text="android-remove" />
        <m-grid-item icon="android-remove-circle" text="android-remove-circle" />
        <m-grid-item icon="android-restaurant" text="android-restaurant" />
        <m-grid-item icon="android-sad" text="android-sad" />
        <m-grid-item icon="android-search" text="android-search" />
        <m-grid-item icon="android-send" text="android-send" />
        <m-grid-item icon="android-settings" text="android-settings" />
        <m-grid-item icon="android-share" text="android-share" />
        <m-grid-item icon="android-share-alt" text="android-share-alt" />
        <m-grid-item icon="android-star" text="android-star" />
        <m-grid-item icon="android-star-half" text="android-star-half" />
        <m-grid-item icon="android-star-outline" text="android-star-outline" />
        <m-grid-item icon="android-stopwatch" text="android-stopwatch" />
        <m-grid-item icon="android-subway" text="android-subway" />
        <m-grid-item icon="android-sunny" text="android-sunny" />
        <m-grid-item icon="android-sync" text="android-sync" />
        <m-grid-item icon="android-textsms" text="android-textsms" />
        <m-grid-item icon="android-time" text="android-time" />
        <m-grid-item icon="android-train" text="android-train" />
        <m-grid-item icon="android-unlock" text="android-unlock" />
        <m-grid-item icon="android-upload" text="android-upload" />
        <m-grid-item icon="android-volume-down" text="android-volume-down" />
        <m-grid-item icon="android-volume-mute" text="android-volume-mute" />
        <m-grid-item icon="android-volume-off" text="android-volume-off" />
        <m-grid-item icon="android-volume-up" text="android-volume-up" />
        <m-grid-item icon="android-walk" text="android-walk" />
        <m-grid-item icon="android-warning" text="android-warning" />
        <m-grid-item icon="android-watch" text="android-watch" />
        <m-grid-item icon="android-wifi" text="android-wifi" />
        <m-grid-item icon="aperture" text="aperture" />
        <m-grid-item icon="archive" text="archive" />
        <m-grid-item icon="arrow-down-a" text="arrow-down-a" />
        <m-grid-item icon="arrow-down-b" text="arrow-down-b" />
        <m-grid-item icon="arrow-down-c" text="arrow-down-c" />
        <m-grid-item icon="arrow-expand" text="arrow-expand" />
        <m-grid-item icon="arrow-graph-down-left" text="arrow-graph-down-left" />
        <m-grid-item icon="arrow-graph-down-right" text="arrow-graph-down-right" />
        <m-grid-item icon="arrow-graph-up-left" text="arrow-graph-up-left" />
        <m-grid-item icon="arrow-graph-up-right" text="arrow-graph-up-right" />
        <m-grid-item icon="arrow-left-a" text="arrow-left-a" />
        <m-grid-item icon="arrow-left-b" text="arrow-left-b" />
        <m-grid-item icon="arrow-left-c" text="arrow-left-c" />
        <m-grid-item icon="arrow-move" text="arrow-move" />
        <m-grid-item icon="arrow-resize" text="arrow-resize" />
        <m-grid-item icon="arrow-return-left" text="arrow-return-left" />
        <m-grid-item icon="arrow-return-right" text="arrow-return-right" />
        <m-grid-item icon="arrow-right-a" text="arrow-right-a" />
        <m-grid-item icon="arrow-right-b" text="arrow-right-b" />
        <m-grid-item icon="arrow-right-c" text="arrow-right-c" />
        <m-grid-item icon="arrow-shrink" text="arrow-shrink" />
        <m-grid-item icon="arrow-swap" text="arrow-swap" />
        <m-grid-item icon="arrow-up-a" text="arrow-up-a" />
        <m-grid-item icon="arrow-up-b" text="arrow-up-b" />
        <m-grid-item icon="arrow-up-c" text="arrow-up-c" />
        <m-grid-item icon="asterisk" text="asterisk" />
        <m-grid-item icon="at" text="at" />
        <m-grid-item icon="backspace" text="backspace" />
        <m-grid-item icon="backspace-outline" text="backspace-outline" />
        <m-grid-item icon="bag" text="bag" />
        <m-grid-item icon="battery-charging" text="battery-charging" />
        <m-grid-item icon="battery-empty" text="battery-empty" />
        <m-grid-item icon="battery-full" text="battery-full" />
        <m-grid-item icon="battery-half" text="battery-half" />
        <m-grid-item icon="battery-low" text="battery-low" />
        <m-grid-item icon="beaker" text="beaker" />
        <m-grid-item icon="beer" text="beer" />
        <m-grid-item icon="bluetooth" text="bluetooth" />
        <m-grid-item icon="bonfire" text="bonfire" />
        <m-grid-item icon="bookmark" text="bookmark" />
        <m-grid-item icon="bowtie" text="bowtie" />
        <m-grid-item icon="briefcase" text="briefcase" />
        <m-grid-item icon="bug" text="bug" />
        <m-grid-item icon="calculator" text="calculator" />
        <m-grid-item icon="calendar" text="calendar" />
        <m-grid-item icon="camera" text="camera" />
        <m-grid-item icon="card" text="card" />
        <m-grid-item icon="cash" text="cash" />
        <m-grid-item icon="chatbox" text="chatbox" />
        <m-grid-item icon="chatbox-working" text="chatbox-working" />
        <m-grid-item icon="chatboxes" text="chatboxes" />
        <m-grid-item icon="chatbubble" text="chatbubble" />
        <m-grid-item icon="chatbubble-working" text="chatbubble-working" />
        <m-grid-item icon="chatbubbles" text="chatbubbles" />
        <m-grid-item icon="checkmark" text="checkmark" />
        <m-grid-item icon="checkmark-circled" text="checkmark-circled" />
        <m-grid-item icon="checkmark-round" text="checkmark-round" />
        <m-grid-item icon="chevron-down" text="chevron-down" />
        <m-grid-item icon="chevron-left" text="chevron-left" />
        <m-grid-item icon="chevron-right" text="chevron-right" />
        <m-grid-item icon="chevron-up" text="chevron-up" />
        <m-grid-item icon="clipboard" text="clipboard" />
        <m-grid-item icon="clock" text="clock" />
        <m-grid-item icon="close" text="close" />
        <m-grid-item icon="close-circled" text="close-circled" />
        <m-grid-item icon="close-round" text="close-round" />
        <m-grid-item icon="closed-captioning" text="closed-captioning" />
        <m-grid-item icon="cloud" text="cloud" />
        <m-grid-item icon="code" text="code" />
        <m-grid-item icon="code-download" text="code-download" />
        <m-grid-item icon="code-working" text="code-working" />
        <m-grid-item icon="coffee" text="coffee" />
        <m-grid-item icon="compass" text="compass" />
        <m-grid-item icon="compose" text="compose" />
        <m-grid-item icon="connection-bars" text="connection-bars" />
        <m-grid-item icon="contrast" text="contrast" />
        <m-grid-item icon="crop" text="crop" />
        <m-grid-item icon="cube" text="cube" />
        <m-grid-item icon="disc" text="disc" />
        <m-grid-item icon="document" text="document" />
        <m-grid-item icon="document-text" text="document-text" />
        <m-grid-item icon="drag" text="drag" />
        <m-grid-item icon="earth" text="earth" />
        <m-grid-item icon="easel" text="easel" />
        <m-grid-item icon="edit" text="edit" />
        <m-grid-item icon="egg" text="egg" />
        <m-grid-item icon="eject" text="eject" />
        <m-grid-item icon="email" text="email" />
        <m-grid-item icon="email-unread" text="email-unread" />
        <m-grid-item icon="erlenmeyer-flask" text="erlenmeyer-flask" />
        <m-grid-item icon="erlenmeyer-flask-bubbles" text="erlenmeyer-flask-bubbles" />
        <m-grid-item icon="eye" text="eye" />
        <m-grid-item icon="eye-disabled" text="eye-disabled" />
        <m-grid-item icon="female" text="female" />
        <m-grid-item icon="filing" text="filing" />
        <m-grid-item icon="film-marker" text="film-marker" />
        <m-grid-item icon="fireball" text="fireball" />
        <m-grid-item icon="flag" text="flag" />
        <m-grid-item icon="flame" text="flame" />
        <m-grid-item icon="flash" text="flash" />
        <m-grid-item icon="flash-off" text="flash-off" />
        <m-grid-item icon="folder" text="folder" />
        <m-grid-item icon="fork" text="fork" />
        <m-grid-item icon="fork-repo" text="fork-repo" />
        <m-grid-item icon="forward" text="forward" />
        <m-grid-item icon="funnel" text="funnel" />
        <m-grid-item icon="gear-a" text="gear-a" />
        <m-grid-item icon="gear-b" text="gear-b" />
        <m-grid-item icon="grid" text="grid" />
        <m-grid-item icon="hammer" text="hammer" />
        <m-grid-item icon="happy" text="happy" />
        <m-grid-item icon="happy-outline" text="happy-outline" />
        <m-grid-item icon="headphone" text="headphone" />
        <m-grid-item icon="heart" text="heart" />
        <m-grid-item icon="heart-broken" text="heart-broken" />
        <m-grid-item icon="help" text="help" />
        <m-grid-item icon="help-buoy" text="help-buoy" />
        <m-grid-item icon="help-circled" text="help-circled" />
        <m-grid-item icon="home" text="home" />
        <m-grid-item icon="icecream" text="icecream" />
        <m-grid-item icon="image" text="image" />
        <m-grid-item icon="images" text="images" />
        <m-grid-item icon="information" text="information" />
        <m-grid-item icon="information-circled" text="information-circled" />
        <m-grid-item icon="ionic" text="ionic" />
        <m-grid-item icon="ios-alarm" text="ios-alarm" />
        <m-grid-item icon="ios-alarm-outline" text="ios-alarm-outline" />
        <m-grid-item icon="ios-albums" text="ios-albums" />
        <m-grid-item icon="ios-albums-outline" text="ios-albums-outline" />
        <m-grid-item icon="ios-americanfootball" text="ios-americanfootball" />
        <m-grid-item icon="ios-americanfootball-outline" text="ios-americanfootball-outline" />
        <m-grid-item icon="ios-analytics" text="ios-analytics" />
        <m-grid-item icon="ios-analytics-outline" text="ios-analytics-outline" />
        <m-grid-item icon="ios-arrow-back" text="ios-arrow-back" />
        <m-grid-item icon="ios-arrow-down" text="ios-arrow-down" />
        <m-grid-item icon="ios-arrow-forward" text="ios-arrow-forward" />
        <m-grid-item icon="ios-arrow-left" text="ios-arrow-left" />
        <m-grid-item icon="ios-arrow-right" text="ios-arrow-right" />
        <m-grid-item icon="ios-arrow-thin-down" text="ios-arrow-thin-down" />
        <m-grid-item icon="ios-arrow-thin-left" text="ios-arrow-thin-left" />
        <m-grid-item icon="ios-arrow-thin-right" text="ios-arrow-thin-right" />
        <m-grid-item icon="ios-arrow-thin-up" text="ios-arrow-thin-up" />
        <m-grid-item icon="ios-arrow-up" text="ios-arrow-up" />
        <m-grid-item icon="ios-at" text="ios-at" />
        <m-grid-item icon="ios-at-outline" text="ios-at-outline" />
        <m-grid-item icon="ios-barcode" text="ios-barcode" />
        <m-grid-item icon="ios-barcode-outline" text="ios-barcode-outline" />
        <m-grid-item icon="ios-baseball" text="ios-baseball" />
        <m-grid-item icon="ios-baseball-outline" text="ios-baseball-outline" />
        <m-grid-item icon="ios-basketball" text="ios-basketball" />
        <m-grid-item icon="ios-basketball-outline" text="ios-basketball-outline" />
        <m-grid-item icon="ios-bell" text="ios-bell" />
        <m-grid-item icon="ios-bell-outline" text="ios-bell-outline" />
        <m-grid-item icon="ios-body" text="ios-body" />
        <m-grid-item icon="ios-body-outline" text="ios-body-outline" />
        <m-grid-item icon="ios-bolt" text="ios-bolt" />
        <m-grid-item icon="ios-bolt-outline" text="ios-bolt-outline" />
        <m-grid-item icon="ios-book" text="ios-book" />
        <m-grid-item icon="ios-book-outline" text="ios-book-outline" />
        <m-grid-item icon="ios-bookmarks" text="ios-bookmarks" />
        <m-grid-item icon="ios-bookmarks-outline" text="ios-bookmarks-outline" />
        <m-grid-item icon="ios-box" text="ios-box" />
        <m-grid-item icon="ios-box-outline" text="ios-box-outline" />
        <m-grid-item icon="ios-briefcase" text="ios-briefcase" />
        <m-grid-item icon="ios-briefcase-outline" text="ios-briefcase-outline" />
        <m-grid-item icon="ios-browsers" text="ios-browsers" />
        <m-grid-item icon="ios-browsers-outline" text="ios-browsers-outline" />
        <m-grid-item icon="ios-calculator" text="ios-calculator" />
        <m-grid-item icon="ios-calculator-outline" text="ios-calculator-outline" />
        <m-grid-item icon="ios-calendar" text="ios-calendar" />
        <m-grid-item icon="ios-calendar-outline" text="ios-calendar-outline" />
        <m-grid-item icon="ios-camera" text="ios-camera" />
        <m-grid-item icon="ios-camera-outline" text="ios-camera-outline" />
        <m-grid-item icon="ios-cart" text="ios-cart" />
        <m-grid-item icon="ios-cart-outline" text="ios-cart-outline" />
        <m-grid-item icon="ios-chatboxes" text="ios-chatboxes" />
        <m-grid-item icon="ios-chatboxes-outline" text="ios-chatboxes-outline" />
        <m-grid-item icon="ios-chatbubble" text="ios-chatbubble" />
        <m-grid-item icon="ios-chatbubble-outline" text="ios-chatbubble-outline" />
        <m-grid-item icon="ios-checkmark" text="ios-checkmark" />
        <m-grid-item icon="ios-checkmark-empty" text="ios-checkmark-empty" />
        <m-grid-item icon="ios-checkmark-outline" text="ios-checkmark-outline" />
        <m-grid-item icon="ios-circle-filled" text="ios-circle-filled" />
        <m-grid-item icon="ios-circle-outline" text="ios-circle-outline" />
        <m-grid-item icon="ios-clock" text="ios-clock" />
        <m-grid-item icon="ios-clock-outline" text="ios-clock-outline" />
        <m-grid-item icon="ios-close" text="ios-close" />
        <m-grid-item icon="ios-close-empty" text="ios-close-empty" />
        <m-grid-item icon="ios-close-outline" text="ios-close-outline" />
        <m-grid-item icon="ios-cloud" text="ios-cloud" />
        <m-grid-item icon="ios-cloud-download" text="ios-cloud-download" />
        <m-grid-item icon="ios-cloud-download-outline" text="ios-cloud-download-outline" />
        <m-grid-item icon="ios-cloud-outline" text="ios-cloud-outline" />
        <m-grid-item icon="ios-cloud-upload" text="ios-cloud-upload" />
        <m-grid-item icon="ios-cloud-upload-outline" text="ios-cloud-upload-outline" />
        <m-grid-item icon="ios-cloudy" text="ios-cloudy" />
        <m-grid-item icon="ios-cloudy-night" text="ios-cloudy-night" />
        <m-grid-item icon="ios-cloudy-night-outline" text="ios-cloudy-night-outline" />
        <m-grid-item icon="ios-cloudy-outline" text="ios-cloudy-outline" />
        <m-grid-item icon="ios-cog" text="ios-cog" />
        <m-grid-item icon="ios-cog-outline" text="ios-cog-outline" />
        <m-grid-item icon="ios-color-filter" text="ios-color-filter" />
        <m-grid-item icon="ios-color-filter-outline" text="ios-color-filter-outline" />
        <m-grid-item icon="ios-color-wand" text="ios-color-wand" />
        <m-grid-item icon="ios-color-wand-outline" text="ios-color-wand-outline" />
        <m-grid-item icon="ios-compose" text="ios-compose" />
        <m-grid-item icon="ios-compose-outline" text="ios-compose-outline" />
        <m-grid-item icon="ios-contact" text="ios-contact" />
        <m-grid-item icon="ios-contact-outline" text="ios-contact-outline" />
        <m-grid-item icon="ios-copy" text="ios-copy" />
        <m-grid-item icon="ios-copy-outline" text="ios-copy-outline" />
        <m-grid-item icon="ios-crop" text="ios-crop" />
        <m-grid-item icon="ios-crop-strong" text="ios-crop-strong" />
        <m-grid-item icon="ios-download" text="ios-download" />
        <m-grid-item icon="ios-download-outline" text="ios-download-outline" />
        <m-grid-item icon="ios-drag" text="ios-drag" />
        <m-grid-item icon="ios-email" text="ios-email" />
        <m-grid-item icon="ios-email-outline" text="ios-email-outline" />
        <m-grid-item icon="ios-eye" text="ios-eye" />
        <m-grid-item icon="ios-eye-outline" text="ios-eye-outline" />
        <m-grid-item icon="ios-fastforward" text="ios-fastforward" />
        <m-grid-item icon="ios-fastforward-outline" text="ios-fastforward-outline" />
        <m-grid-item icon="ios-filing" text="ios-filing" />
        <m-grid-item icon="ios-filing-outline" text="ios-filing-outline" />
        <m-grid-item icon="ios-film" text="ios-film" />
        <m-grid-item icon="ios-film-outline" text="ios-film-outline" />
        <m-grid-item icon="ios-flag" text="ios-flag" />
        <m-grid-item icon="ios-flag-outline" text="ios-flag-outline" />
        <m-grid-item icon="ios-flame" text="ios-flame" />
        <m-grid-item icon="ios-flame-outline" text="ios-flame-outline" />
        <m-grid-item icon="ios-flask" text="ios-flask" />
        <m-grid-item icon="ios-flask-outline" text="ios-flask-outline" />
        <m-grid-item icon="ios-flower" text="ios-flower" />
        <m-grid-item icon="ios-flower-outline" text="ios-flower-outline" />
        <m-grid-item icon="ios-folder" text="ios-folder" />
        <m-grid-item icon="ios-folder-outline" text="ios-folder-outline" />
        <m-grid-item icon="ios-football" text="ios-football" />
        <m-grid-item icon="ios-football-outline" text="ios-football-outline" />
        <m-grid-item icon="ios-game-controller-a" text="ios-game-controller-a" />
        <m-grid-item icon="ios-game-controller-a-outline" text="ios-game-controller-a-outline" />
        <m-grid-item icon="ios-game-controller-b" text="ios-game-controller-b" />
        <m-grid-item icon="ios-game-controller-b-outline" text="ios-game-controller-b-outline" />
        <m-grid-item icon="ios-gear" text="ios-gear" />
        <m-grid-item icon="ios-gear-outline" text="ios-gear-outline" />
        <m-grid-item icon="ios-glasses" text="ios-glasses" />
        <m-grid-item icon="ios-glasses-outline" text="ios-glasses-outline" />
        <m-grid-item icon="ios-grid-view" text="ios-grid-view" />
        <m-grid-item icon="ios-grid-view-outline" text="ios-grid-view-outline" />
        <m-grid-item icon="ios-heart" text="ios-heart" />
        <m-grid-item icon="ios-heart-outline" text="ios-heart-outline" />
        <m-grid-item icon="ios-help" text="ios-help" />
        <m-grid-item icon="ios-help-empty" text="ios-help-empty" />
        <m-grid-item icon="ios-help-outline" text="ios-help-outline" />
        <m-grid-item icon="ios-home" text="ios-home" />
        <m-grid-item icon="ios-home-outline" text="ios-home-outline" />
        <m-grid-item icon="ios-infinite" text="ios-infinite" />
        <m-grid-item icon="ios-infinite-outline" text="ios-infinite-outline" />
        <m-grid-item icon="ios-information" text="ios-information" />
        <m-grid-item icon="ios-information-empty" text="ios-information-empty" />
        <m-grid-item icon="ios-information-outline" text="ios-information-outline" />
        <m-grid-item icon="ios-ionic-outline" text="ios-ionic-outline" />
        <m-grid-item icon="ios-keypad" text="ios-keypad" />
        <m-grid-item icon="ios-keypad-outline" text="ios-keypad-outline" />
        <m-grid-item icon="ios-lightbulb" text="ios-lightbulb" />
        <m-grid-item icon="ios-lightbulb-outline" text="ios-lightbulb-outline" />
        <m-grid-item icon="ios-list" text="ios-list" />
        <m-grid-item icon="ios-list-outline" text="ios-list-outline" />
        <m-grid-item icon="ios-location" text="ios-location" />
        <m-grid-item icon="ios-location-outline" text="ios-location-outline" />
        <m-grid-item icon="ios-locked" text="ios-locked" />
        <m-grid-item icon="ios-locked-outline" text="ios-locked-outline" />
        <m-grid-item icon="ios-loop" text="ios-loop" />
        <m-grid-item icon="ios-loop-strong" text="ios-loop-strong" />
        <m-grid-item icon="ios-medical" text="ios-medical" />
        <m-grid-item icon="ios-medical-outline" text="ios-medical-outline" />
        <m-grid-item icon="ios-medkit" text="ios-medkit" />
        <m-grid-item icon="ios-medkit-outline" text="ios-medkit-outline" />
        <m-grid-item icon="ios-mic" text="ios-mic" />
        <m-grid-item icon="ios-mic-off" text="ios-mic-off" />
        <m-grid-item icon="ios-mic-outline" text="ios-mic-outline" />
        <m-grid-item icon="ios-minus" text="ios-minus" />
        <m-grid-item icon="ios-minus-empty" text="ios-minus-empty" />
        <m-grid-item icon="ios-minus-outline" text="ios-minus-outline" />
        <m-grid-item icon="ios-monitor" text="ios-monitor" />
        <m-grid-item icon="ios-monitor-outline" text="ios-monitor-outline" />
        <m-grid-item icon="ios-moon" text="ios-moon" />
        <m-grid-item icon="ios-moon-outline" text="ios-moon-outline" />
        <m-grid-item icon="ios-more" text="ios-more" />
        <m-grid-item icon="ios-more-outline" text="ios-more-outline" />
        <m-grid-item icon="ios-musical-note" text="ios-musical-note" />
        <m-grid-item icon="ios-musical-notes" text="ios-musical-notes" />
        <m-grid-item icon="ios-navigate" text="ios-navigate" />
        <m-grid-item icon="ios-navigate-outline" text="ios-navigate-outline" />
        <m-grid-item icon="ios-nutrition" text="ios-nutrition" />
        <m-grid-item icon="ios-nutrition-outline" text="ios-nutrition-outline" />
        <m-grid-item icon="ios-paper" text="ios-paper" />
        <m-grid-item icon="ios-paper-outline" text="ios-paper-outline" />
        <m-grid-item icon="ios-paperplane" text="ios-paperplane" />
        <m-grid-item icon="ios-paperplane-outline" text="ios-paperplane-outline" />
        <m-grid-item icon="ios-partlysunny" text="ios-partlysunny" />
        <m-grid-item icon="ios-partlysunny-outline" text="ios-partlysunny-outline" />
        <m-grid-item icon="ios-pause" text="ios-pause" />
        <m-grid-item icon="ios-pause-outline" text="ios-pause-outline" />
        <m-grid-item icon="ios-paw" text="ios-paw" />
        <m-grid-item icon="ios-paw-outline" text="ios-paw-outline" />
        <m-grid-item icon="ios-people" text="ios-people" />
        <m-grid-item icon="ios-people-outline" text="ios-people-outline" />
        <m-grid-item icon="ios-person" text="ios-person" />
        <m-grid-item icon="ios-person-outline" text="ios-person-outline" />
        <m-grid-item icon="ios-personadd" text="ios-personadd" />
        <m-grid-item icon="ios-personadd-outline" text="ios-personadd-outline" />
        <m-grid-item icon="ios-photos" text="ios-photos" />
        <m-grid-item icon="ios-photos-outline" text="ios-photos-outline" />
        <m-grid-item icon="ios-pie" text="ios-pie" />
        <m-grid-item icon="ios-pie-outline" text="ios-pie-outline" />
        <m-grid-item icon="ios-pint" text="ios-pint" />
        <m-grid-item icon="ios-pint-outline" text="ios-pint-outline" />
        <m-grid-item icon="ios-play" text="ios-play" />
        <m-grid-item icon="ios-play-outline" text="ios-play-outline" />
        <m-grid-item icon="ios-plus" text="ios-plus" />
        <m-grid-item icon="ios-plus-empty" text="ios-plus-empty" />
        <m-grid-item icon="ios-plus-outline" text="ios-plus-outline" />
        <m-grid-item icon="ios-pricetag" text="ios-pricetag" />
        <m-grid-item icon="ios-pricetag-outline" text="ios-pricetag-outline" />
        <m-grid-item icon="ios-pricetags" text="ios-pricetags" />
        <m-grid-item icon="ios-pricetags-outline" text="ios-pricetags-outline" />
        <m-grid-item icon="ios-printer" text="ios-printer" />
        <m-grid-item icon="ios-printer-outline" text="ios-printer-outline" />
        <m-grid-item icon="ios-pulse" text="ios-pulse" />
        <m-grid-item icon="ios-pulse-strong" text="ios-pulse-strong" />
        <m-grid-item icon="ios-rainy" text="ios-rainy" />
        <m-grid-item icon="ios-rainy-outline" text="ios-rainy-outline" />
        <m-grid-item icon="ios-recording" text="ios-recording" />
        <m-grid-item icon="ios-recording-outline" text="ios-recording-outline" />
        <m-grid-item icon="ios-redo" text="ios-redo" />
        <m-grid-item icon="ios-redo-outline" text="ios-redo-outline" />
        <m-grid-item icon="ios-refresh" text="ios-refresh" />
        <m-grid-item icon="ios-refresh-empty" text="ios-refresh-empty" />
        <m-grid-item icon="ios-refresh-outline" text="ios-refresh-outline" />
        <m-grid-item icon="ios-reload" text="ios-reload" />
        <m-grid-item icon="ios-reverse-camera" text="ios-reverse-camera" />
        <m-grid-item icon="ios-reverse-camera-outline" text="ios-reverse-camera-outline" />
        <m-grid-item icon="ios-rewind" text="ios-rewind" />
        <m-grid-item icon="ios-rewind-outline" text="ios-rewind-outline" />
        <m-grid-item icon="ios-rose" text="ios-rose" />
        <m-grid-item icon="ios-rose-outline" text="ios-rose-outline" />
        <m-grid-item icon="ios-search" text="ios-search" />
        <m-grid-item icon="ios-search-strong" text="ios-search-strong" />
        <m-grid-item icon="ios-settings" text="ios-settings" />
        <m-grid-item icon="ios-settings-strong" text="ios-settings-strong" />
        <m-grid-item icon="ios-shuffle" text="ios-shuffle" />
        <m-grid-item icon="ios-shuffle-strong" text="ios-shuffle-strong" />
        <m-grid-item icon="ios-skipbackward" text="ios-skipbackward" />
        <m-grid-item icon="ios-skipbackward-outline" text="ios-skipbackward-outline" />
        <m-grid-item icon="ios-skipforward" text="ios-skipforward" />
        <m-grid-item icon="ios-skipforward-outline" text="ios-skipforward-outline" />
        <m-grid-item icon="ios-snowy" text="ios-snowy" />
        <m-grid-item icon="ios-speedometer" text="ios-speedometer" />
        <m-grid-item icon="ios-speedometer-outline" text="ios-speedometer-outline" />
        <m-grid-item icon="ios-star" text="ios-star" />
        <m-grid-item icon="ios-star-half" text="ios-star-half" />
        <m-grid-item icon="ios-star-outline" text="ios-star-outline" />
        <m-grid-item icon="ios-stopwatch" text="ios-stopwatch" />
        <m-grid-item icon="ios-stopwatch-outline" text="ios-stopwatch-outline" />
        <m-grid-item icon="ios-sunny" text="ios-sunny" />
        <m-grid-item icon="ios-sunny-outline" text="ios-sunny-outline" />
        <m-grid-item icon="ios-telephone" text="ios-telephone" />
        <m-grid-item icon="ios-telephone-outline" text="ios-telephone-outline" />
        <m-grid-item icon="ios-tennisball" text="ios-tennisball" />
        <m-grid-item icon="ios-tennisball-outline" text="ios-tennisball-outline" />
        <m-grid-item icon="ios-thunderstorm" text="ios-thunderstorm" />
        <m-grid-item icon="ios-thunderstorm-outline" text="ios-thunderstorm-outline" />
        <m-grid-item icon="ios-time" text="ios-time" />
        <m-grid-item icon="ios-time-outline" text="ios-time-outline" />
        <m-grid-item icon="ios-timer" text="ios-timer" />
        <m-grid-item icon="ios-timer-outline" text="ios-timer-outline" />
        <m-grid-item icon="ios-toggle" text="ios-toggle" />
        <m-grid-item icon="ios-toggle-outline" text="ios-toggle-outline" />
        <m-grid-item icon="ios-trash" text="ios-trash" />
        <m-grid-item icon="ios-trash-outline" text="ios-trash-outline" />
        <m-grid-item icon="ios-undo" text="ios-undo" />
        <m-grid-item icon="ios-undo-outline" text="ios-undo-outline" />
        <m-grid-item icon="ios-unlocked" text="ios-unlocked" />
        <m-grid-item icon="ios-unlocked-outline" text="ios-unlocked-outline" />
        <m-grid-item icon="ios-upload" text="ios-upload" />
        <m-grid-item icon="ios-upload-outline" text="ios-upload-outline" />
        <m-grid-item icon="ios-videocam" text="ios-videocam" />
        <m-grid-item icon="ios-videocam-outline" text="ios-videocam-outline" />
        <m-grid-item icon="ios-volume-high" text="ios-volume-high" />
        <m-grid-item icon="ios-volume-low" text="ios-volume-low" />
        <m-grid-item icon="ios-wineglass" text="ios-wineglass" />
        <m-grid-item icon="ios-wineglass-outline" text="ios-wineglass-outline" />
        <m-grid-item icon="ios-world" text="ios-world" />
        <m-grid-item icon="ios-world-outline" text="ios-world-outline" />
        <m-grid-item icon="ipad" text="ipad" />
        <m-grid-item icon="iphone" text="iphone" />
        <m-grid-item icon="ipod" text="ipod" />
        <m-grid-item icon="jet" text="jet" />
        <m-grid-item icon="key" text="key" />
        <m-grid-item icon="knife" text="knife" />
        <m-grid-item icon="laptop" text="laptop" />
        <m-grid-item icon="leaf" text="leaf" />
        <m-grid-item icon="levels" text="levels" />
        <m-grid-item icon="lightbulb" text="lightbulb" />
        <m-grid-item icon="link" text="link" />
        <m-grid-item icon="load-a" text="load-a" />
        <m-grid-item icon="load-b" text="load-b" />
        <m-grid-item icon="load-c" text="load-c" />
        <m-grid-item icon="load-d" text="load-d" />
        <m-grid-item icon="location" text="location" />
        <m-grid-item icon="lock-combination" text="lock-combination" />
        <m-grid-item icon="locked" text="locked" />
        <m-grid-item icon="log-in" text="log-in" />
        <m-grid-item icon="log-out" text="log-out" />
        <m-grid-item icon="loop" text="loop" />
        <m-grid-item icon="magnet" text="magnet" />
        <m-grid-item icon="male" text="male" />
        <m-grid-item icon="man" text="man" />
        <m-grid-item icon="map" text="map" />
        <m-grid-item icon="medkit" text="medkit" />
        <m-grid-item icon="merge" text="merge" />
        <m-grid-item icon="mic-a" text="mic-a" />
        <m-grid-item icon="mic-b" text="mic-b" />
        <m-grid-item icon="mic-c" text="mic-c" />
        <m-grid-item icon="minus" text="minus" />
        <m-grid-item icon="minus-circled" text="minus-circled" />
        <m-grid-item icon="minus-round" text="minus-round" />
        <m-grid-item icon="model-s" text="model-s" />
        <m-grid-item icon="monitor" text="monitor" />
        <m-grid-item icon="more" text="more" />
        <m-grid-item icon="mouse" text="mouse" />
        <m-grid-item icon="music-note" text="music-note" />
        <m-grid-item icon="navicon" text="navicon" />
        <m-grid-item icon="navicon-round" text="navicon-round" />
        <m-grid-item icon="navigate" text="navigate" />
        <m-grid-item icon="network" text="network" />
        <m-grid-item icon="no-smoking" text="no-smoking" />
        <m-grid-item icon="nuclear" text="nuclear" />
        <m-grid-item icon="outlet" text="outlet" />
        <m-grid-item icon="paintbrush" text="paintbrush" />
        <m-grid-item icon="paintbucket" text="paintbucket" />
        <m-grid-item icon="paper-airplane" text="paper-airplane" />
        <m-grid-item icon="paperclip" text="paperclip" />
        <m-grid-item icon="pause" text="pause" />
        <m-grid-item icon="person" text="person" />
        <m-grid-item icon="person-add" text="person-add" />
        <m-grid-item icon="person-stalker" text="person-stalker" />
        <m-grid-item icon="pie-graph" text="pie-graph" />
        <m-grid-item icon="pin" text="pin" />
        <m-grid-item icon="pinpoint" text="pinpoint" />
        <m-grid-item icon="pizza" text="pizza" />
        <m-grid-item icon="plane" text="plane" />
        <m-grid-item icon="planet" text="planet" />
        <m-grid-item icon="play" text="play" />
        <m-grid-item icon="playstation" text="playstation" />
        <m-grid-item icon="plus" text="plus" />
        <m-grid-item icon="plus-circled" text="plus-circled" />
        <m-grid-item icon="plus-round" text="plus-round" />
        <m-grid-item icon="podium" text="podium" />
        <m-grid-item icon="pound" text="pound" />
        <m-grid-item icon="power" text="power" />
        <m-grid-item icon="pricetag" text="pricetag" />
        <m-grid-item icon="pricetags" text="pricetags" />
        <m-grid-item icon="printer" text="printer" />
        <m-grid-item icon="pull-request" text="pull-request" />
        <m-grid-item icon="qr-scanner" text="qr-scanner" />
        <m-grid-item icon="quote" text="quote" />
        <m-grid-item icon="radio-waves" text="radio-waves" />
        <m-grid-item icon="record" text="record" />
        <m-grid-item icon="refresh" text="refresh" />
        <m-grid-item icon="reply" text="reply" />
        <m-grid-item icon="reply-all" text="reply-all" />
        <m-grid-item icon="ribbon-a" text="ribbon-a" />
        <m-grid-item icon="ribbon-b" text="ribbon-b" />
        <m-grid-item icon="sad" text="sad" />
        <m-grid-item icon="sad-outline" text="sad-outline" />
        <m-grid-item icon="scissors" text="scissors" />
        <m-grid-item icon="search" text="search" />
        <m-grid-item icon="settings" text="settings" />
        <m-grid-item icon="share" text="share" />
        <m-grid-item icon="shuffle" text="shuffle" />
        <m-grid-item icon="skip-backward" text="skip-backward" />
        <m-grid-item icon="skip-forward" text="skip-forward" />
        <m-grid-item icon="social-android" text="social-android" />
        <m-grid-item icon="social-android-outline" text="social-android-outline" />
        <m-grid-item icon="social-angular" text="social-angular" />
        <m-grid-item icon="social-angular-outline" text="social-angular-outline" />
        <m-grid-item icon="social-apple" text="social-apple" />
        <m-grid-item icon="social-apple-outline" text="social-apple-outline" />
        <m-grid-item icon="social-bitcoin" text="social-bitcoin" />
        <m-grid-item icon="social-bitcoin-outline" text="social-bitcoin-outline" />
        <m-grid-item icon="social-buffer" text="social-buffer" />
        <m-grid-item icon="social-buffer-outline" text="social-buffer-outline" />
        <m-grid-item icon="social-chrome" text="social-chrome" />
        <m-grid-item icon="social-chrome-outline" text="social-chrome-outline" />
        <m-grid-item icon="social-codepen" text="social-codepen" />
        <m-grid-item icon="social-codepen-outline" text="social-codepen-outline" />
        <m-grid-item icon="social-css3" text="social-css3" />
        <m-grid-item icon="social-css3-outline" text="social-css3-outline" />
        <m-grid-item icon="social-designernews" text="social-designernews" />
        <m-grid-item icon="social-designernews-outline" text="social-designernews-outline" />
        <m-grid-item icon="social-dribbble" text="social-dribbble" />
        <m-grid-item icon="social-dribbble-outline" text="social-dribbble-outline" />
        <m-grid-item icon="social-dropbox" text="social-dropbox" />
        <m-grid-item icon="social-dropbox-outline" text="social-dropbox-outline" />
        <m-grid-item icon="social-euro" text="social-euro" />
        <m-grid-item icon="social-euro-outline" text="social-euro-outline" />
        <m-grid-item icon="social-facebook" text="social-facebook" />
        <m-grid-item icon="social-facebook-outline" text="social-facebook-outline" />
        <m-grid-item icon="social-foursquare" text="social-foursquare" />
        <m-grid-item icon="social-foursquare-outline" text="social-foursquare-outline" />
        <m-grid-item icon="social-freebsd-devil" text="social-freebsd-devil" />
        <m-grid-item icon="social-github" text="social-github" />
        <m-grid-item icon="social-github-outline" text="social-github-outline" />
        <m-grid-item icon="social-google" text="social-google" />
        <m-grid-item icon="social-google-outline" text="social-google-outline" />
        <m-grid-item icon="social-googleplus" text="social-googleplus" />
        <m-grid-item icon="social-googleplus-outline" text="social-googleplus-outline" />
        <m-grid-item icon="social-hackernews" text="social-hackernews" />
        <m-grid-item icon="social-hackernews-outline" text="social-hackernews-outline" />
        <m-grid-item icon="social-html5" text="social-html5" />
        <m-grid-item icon="social-html5-outline" text="social-html5-outline" />
        <m-grid-item icon="social-instagram" text="social-instagram" />
        <m-grid-item icon="social-instagram-outline" text="social-instagram-outline" />
        <m-grid-item icon="social-javascript" text="social-javascript" />
        <m-grid-item icon="social-javascript-outline" text="social-javascript-outline" />
        <m-grid-item icon="social-linkedin" text="social-linkedin" />
        <m-grid-item icon="social-linkedin-outline" text="social-linkedin-outline" />
        <m-grid-item icon="social-markdown" text="social-markdown" />
        <m-grid-item icon="social-nodejs" text="social-nodejs" />
        <m-grid-item icon="social-octocat" text="social-octocat" />
        <m-grid-item icon="social-pinterest" text="social-pinterest" />
        <m-grid-item icon="social-pinterest-outline" text="social-pinterest-outline" />
        <m-grid-item icon="social-python" text="social-python" />
        <m-grid-item icon="social-reddit" text="social-reddit" />
        <m-grid-item icon="social-reddit-outline" text="social-reddit-outline" />
        <m-grid-item icon="social-rss" text="social-rss" />
        <m-grid-item icon="social-rss-outline" text="social-rss-outline" />
        <m-grid-item icon="social-sass" text="social-sass" />
        <m-grid-item icon="social-skype" text="social-skype" />
        <m-grid-item icon="social-skype-outline" text="social-skype-outline" />
        <m-grid-item icon="social-snapchat" text="social-snapchat" />
        <m-grid-item icon="social-snapchat-outline" text="social-snapchat-outline" />
        <m-grid-item icon="social-tumblr" text="social-tumblr" />
        <m-grid-item icon="social-tumblr-outline" text="social-tumblr-outline" />
        <m-grid-item icon="social-tux" text="social-tux" />
        <m-grid-item icon="social-twitch" text="social-twitch" />
        <m-grid-item icon="social-twitch-outline" text="social-twitch-outline" />
        <m-grid-item icon="social-twitter" text="social-twitter" />
        <m-grid-item icon="social-twitter-outline" text="social-twitter-outline" />
        <m-grid-item icon="social-usd" text="social-usd" />
        <m-grid-item icon="social-usd-outline" text="social-usd-outline" />
        <m-grid-item icon="social-vimeo" text="social-vimeo" />
        <m-grid-item icon="social-vimeo-outline" text="social-vimeo-outline" />
        <m-grid-item icon="social-whatsapp" text="social-whatsapp" />
        <m-grid-item icon="social-whatsapp-outline" text="social-whatsapp-outline" />
        <m-grid-item icon="social-windows" text="social-windows" />
        <m-grid-item icon="social-windows-outline" text="social-windows-outline" />
        <m-grid-item icon="social-wordpress" text="social-wordpress" />
        <m-grid-item icon="social-wordpress-outline" text="social-wordpress-outline" />
        <m-grid-item icon="social-yahoo" text="social-yahoo" />
        <m-grid-item icon="social-yahoo-outline" text="social-yahoo-outline" />
        <m-grid-item icon="social-yen" text="social-yen" />
        <m-grid-item icon="social-yen-outline" text="social-yen-outline" />
        <m-grid-item icon="social-youtube" text="social-youtube" />
        <m-grid-item icon="social-youtube-outline" text="social-youtube-outline" />
        <m-grid-item icon="soup-can" text="soup-can" />
        <m-grid-item icon="soup-can-outline" text="soup-can-outline" />
        <m-grid-item icon="speakerphone" text="speakerphone" />
        <m-grid-item icon="speedometer" text="speedometer" />
        <m-grid-item icon="spoon" text="spoon" />
        <m-grid-item icon="star" text="star" />
        <m-grid-item icon="stats-bars" text="stats-bars" />
        <m-grid-item icon="steam" text="steam" />
        <m-grid-item icon="stop" text="stop" />
        <m-grid-item icon="thermometer" text="thermometer" />
        <m-grid-item icon="thumbsdown" text="thumbsdown" />
        <m-grid-item icon="thumbsup" text="thumbsup" />
        <m-grid-item icon="toggle" text="toggle" />
        <m-grid-item icon="toggle-filled" text="toggle-filled" />
        <m-grid-item icon="transgender" text="transgender" />
        <m-grid-item icon="trash-a" text="trash-a" />
        <m-grid-item icon="trash-b" text="trash-b" />
        <m-grid-item icon="trophy" text="trophy" />
        <m-grid-item icon="tshirt" text="tshirt" />
        <m-grid-item icon="tshirt-outline" text="tshirt-outline" />
        <m-grid-item icon="umbrella" text="umbrella" />
        <m-grid-item icon="university" text="university" />
        <m-grid-item icon="unlocked" text="unlocked" />
        <m-grid-item icon="upload" text="upload" />
        <m-grid-item icon="usb" text="usb" />
        <m-grid-item icon="videocamera" text="videocamera" />
        <m-grid-item icon="volume-high" text="volume-high" />
        <m-grid-item icon="volume-low" text="volume-low" />
        <m-grid-item icon="volume-medium" text="volume-medium" />
        <m-grid-item icon="volume-mute" text="volume-mute" />
        <m-grid-item icon="wand" text="wand" />
        <m-grid-item icon="waterdrop" text="waterdrop" />
        <m-grid-item icon="wifi" text="wifi" />
        <m-grid-item icon="wineglass" text="wineglass" />
        <m-grid-item icon="woman" text="woman" />
        <m-grid-item icon="wrench" text="wrench" />
        <m-grid-item icon="xbox" text="xbox" />
      </m-grid>
    </div>
  </div>
</template>

<script>
import Content from '../doc/Icon'

export default {
  name: 'exp-icon',
  components: { DocContent: Content }
}
</script>

<style lang="scss" scoped>
@import '@/common/css/global.scss';
</style>
